### ISSUE TITLE
obsidian-vim not working, am I doing something wrong?

### ISSUE THREAD

**Issue by johnny-liaw** [esm7/obsidian-vimrc-support#1]
Hey I've installed the obsidian-vim plugin and created a .obsidian.vimrc file in vault root dir with some basic commands, however I'm not too sure how to get basic up and down navigation working, do you have any recommendations?

![Screen Shot 2020-11-05 at 8 59 03 pm](https://user-images.githubusercontent.com/18642522/98226191-cdf12880-1fa9-11eb-9cda-8b80a73f3e37.png)

**Comment by esm7** [comment]
Sorry @johnny-liaw I'm not sure I understand the issue.
Just a shot in the dark, but could it be that you don't have Obsidian's Vim mode turned on (via Editor -> Vim key bindings)?

**Comment by johnny-liaw** [comment]
@esm7  thanks a lot man! That did the trick, i enabled the 3rd party plugin but I didn't realise there was another setting in Editor I had to toggle.

**Comment by esm7** [comment]
You're probably not the last who misses this, so I updated the readme accordingly :pray:
