### ISSUE TITLE
Visual line movement gets into a loop in a H1 Heading

### ISSUE THREAD

**Issue by skopjanecot** [esm7/obsidian-vimrc-support#113]
First of all, thanks for this plugin, it's amazingly useful.

As the title says, visual movement mapped as you suggest `nmap j gj` in the `.vimrc` file gets stuck when it encounters a H1 heading and just moves from the beginning of the line to the end. It seems fine with H2 and the rest.

**Comment by esm7** [comment]
Please open this bug with Obsidian, it's not related to this plugin.
It's a very annoying bug for me too :(

**Comment by skopjanecot** [comment]
I'm not sure they will take this issue seriously if I do :)
How do you circumvent the bug?

**Comment by CuteWaterBeary** [comment]
> I'm not sure they will take this issue seriously if I do :) How do you circumvent the bug?

I used a plugin called "Code Editor Shortcuts" then binding a key to its actions "Go to Next Line" or "Move Cursor Down".
