### ISSUE TITLE
Question - remapping default movement

### ISSUE THREAD

**Issue by tallguyjenks** [esm7/obsidian-vimrc-support#12]
Now ive edited vimrc's before but I couldn't get this to work.

i wanted to remap `hjkl` in normal mode to match hand placement for touch typing, i.e.:

`j = h`
`k = j`
`l = k`
`; = l`

I tried using nmap, and even tried using map

what I noticed is that the keys overlap so if I say `j = h` now, then `j` will send me left as `h` used to do. great.

but when i remap `k` to be `j` or to send me "done" as `j` used to do, then it copies `j`'s functionality and will also send me left.

one avenue that almost worked was to map the keys like

`j = g1h`
`k = gj`
`l = gk`
`; = g1l`

but at that point the `;` key doesn't have the intended effect of sending me 1 character to the right as lt has been remapped to mean the operation of the `l` key.

my question is, do you know of a way within the confines of this remplecated vim environment to remap the `hjkl` keys to being `jkl;` for the sake of touch typing?

**Comment by esm7** [comment]
I believe that `map ; <Right>` should fix the last issue you are describing.

**Comment by tallguyjenks** [comment]
I did try that, and it's sending me upwards for some reason


https://user-images.githubusercontent.com/29872822/103373834-df771e00-4a8a-11eb-89eb-bb2fcbdab094.mov

**Comment by esm7** [comment]
Strange, it does work for me.
I assume this problem occurs regardless of whether you have the Vimrc plugin enabled or not. Does it recreate in the CodeMirror [Vim demo](https://codemirror.net/demo/vim.html)? If so, I suggest opening an issue in the CodeMirror Github repo, since they're most likely to be able to help.
