### ISSUE TITLE
FYI - ALL remappings stopped working with v0.15.9, I rolled back for an easy fix.

### ISSUE THREAD

**Issue by cabbott008** [esm7/obsidian-vimrc-support#125]
**Please Review Before Posting!**

- [x ] I'm reasonably sure that this bug is indeed about the Vimrc file support.

**Describe the bug:**
My remappings all stopped working with v0.15.9 installation.

**To Reproduce:**

Install v0.15.9.

**Environment (please complete the following information):**

 - OS: MacOS Version 11.6.8

 - Vimrc plugin version: 0.7.1

**Additional context:**

I rolled back to v0.15.8 and everythings great!

**Comment by esm7** [comment]
Can you check if similarly to https://github.com/esm7/obsidian-vimrc-support/issues/122, this gets resolved if you disable all other plugins and restart Obsidian?

**Comment by esm7** [comment]
Can you please check if the attached main.js file solves the issue (by putting it in the `obsidian-vimrc-support` folder under `.obsidian/plugin` and restarting Obsidian)?
[vimrc.zip](https://github.com/esm7/obsidian-vimrc-support/files/9207159/vimrc.zip)

**Comment by esm7** [comment]
I believe 0.7.2 should fix this issue, please reopen if it doesn't.

**Comment by cabbott008** [comment]
Thank you so much!
