### ISSUE TITLE
Implement repeated motion remaps

### ISSUE THREAD

**Issue by Alex23rodriguez** [esm7/obsidian-vimrc-support#127]
I should be able to remap, for example, J to 5j: `noremap J 5j` for quick motions

**Comment by JeffersonDing** [comment]
This would be an amazing addition. Currently there is no way of quickly moving through the document.

**Comment by Alex23rodriguez** [comment]
so after seeing no progress on this feature I decided to attempt implementing it myself, and noticed that the issue seems to stem from [CodeMirror](https://github.com/replit/codemirror-vim/blob/master/src/vim.js), not this plugin directly... I'll see if I can solve the issue there and make a PR.

**Comment by Alex23rodriguez** [comment]
So after a bit of digging around, I found that you in fact _can_ use repeated motion... just not with `noremap`. That is, you can use the commands that `codemirror-vim` implements with possible recursion: `map`, `nmap`, `imap`, `vmap`. For stuff that's not too complex (such as this case) you should be able to use `map j 5j` and it works properly. 

If you don't have the default key mappings for motion (for example, if you use a different keyboard layout) i'd recommend mapping to the _other_ mapping. For example:
```vim
noremap u k " use u instead of k to move up
map U 5u     " because map U 5k can have weird behavior
```

I'll go ahead and close this issue, as it's not the plugin's fault that noremap isn't yet fully implemented. However, I'll update if and when `codemirror-vim` gets this update.
