### ISSUE TITLE
Could this be made to work with iOS/iPadOS?

### ISSUE THREAD

**Issue by EricEWeir** [esm7/obsidian-vimrc-support#133]
**Please make sure this feature request is within the scope of this plugin.**

- [ x] I understand that if my request is about supporting some Vim feature, it probably belongs [here](https://github.com/replit/codemirror-vim).

**Describe the feature that you'd like:**

New to Obsidian. Use it primarily on iPhone/iPad. I was disappointed to find that your plugin doesn’t work with my device. Would it be possible/not terribly difficult to change that?

**Comment by esm7** [comment]
I bought a Bluetooth keyboard for the purpose of testing the plugin on mobile, but did not yet have the time to work on it.
Hoping to get to it in the upcoming weeks!

**Comment by EricEWeir** [comment]
I’d like to give this plug-in a try in iOS/iPadOS. Don’t see how to install it.

Also, relatively new to Obsidian. Don’t know how to access the root of my vault.

**Comment by Y-S-A** [comment]
> I was able to install the plugin manually on my iPad and it seems to work completely fine. The one problem is installing itself which needs third party apps to edit the .obsidian folder.

Any chance to share how to manually install plugin on ipad? I know how to install plugin on win but have no idea how to do that on ipad. And I searched but found nothing. Thank you very much

**Comment by VAWVAW** [comment]
> > I was able to install the plugin manually on my iPad and it seems to work completely fine. The one problem is installing itself which needs third party apps to edit the .obsidian folder.
> 
> Any chance to share how to manually install plugin on ipad? I know how to install plugin on win but have no idea how to do that on ipad. And I searched but found nothing. Thank you very much

I have the app WebSSH installed which also includes a local terminal. I copied my obsidian vault into the WebSSH folder and used the terminal to access the `.obsidian` folder and add the compiled files manually like you would on a desktop. I also had to toggle the `isDesktopOnly` flag in `manifest.json` to make the plugin load.

**Comment by esm7** [comment]
Added in 0.8.0 :)
