### ISSUE TITLE
Go to definition command

### ISSUE THREAD

**Issue by vimtor** [esm7/obsidian-vimrc-support#136]
I've found the following command really useful so you may want to add it in the README:

```
" Go to definition style for references
exmap definition obcommand editor:open-link-in-new-leaf
nmap gd :definition
```

Thanks for the plugin! It is awesome ❤️

**Comment by sesm** [comment]
Thank you so much! I wanted to ask a question about this, but luckily I found this first.

Note, that if you want to open link in the same editor (for example, cross-link to a different note) and use C-o/C-i navigation, you can do it like this:
```
exmap definition obcommand editor:follow-link
nmap gd :definition
```

**Comment by vimtor** [comment]
Thank you @sesm!

**Comment by nilsherzig** [comment]
ay thanks
