### ISSUE TITLE
noremap not working?

### ISSUE THREAD

**Issue by RobertoGoAm** [esm7/obsidian-vimrc-support#14]
Hey,
I just installed the plugin and tried using my usual vim remaps for COLEMAK and it seems they dont have any effect. Noremap seems to be in the codemirror file, but im not sure whether its usable. Vim is enabled, so is the plugin, it loads without errors in the developer console, .obsidian.vimrc is in the vault root and the config works in vim without issue.

Here are the contents of .obsidian.vimrc:

```
" COLEMAK
noremap i l
noremap l i
noremap n j
noremap j n
noremap e k
noremap k e
noremap I L
noremap L I
noremap N J
noremap J N
noremap E K
noremap K E
```

The goal is for hjkl to be remaped to hnei, e to k, i to l and n to j in all modes but insert. Can you help me out?

**Comment by esm7** [comment]
This command is not part of the default CodeMirror Ex commands, but in a very nice timing @nadavspi posted a PR to add it this weekend :)
https://github.com/esm7/obsidian-vimrc-support/pull/13
(merged it a few mins ago)
