### ISSUE TITLE
Surround action not work well.

### ISSUE THREAD

**Issue by woshichuanqilz** [esm7/obsidian-vimrc-support#142]
**Please Review Before Posting!**

- [ ] I checked that the bug *does not happen* in the [CodeMirror Vim demo](https://codemirror-vim--util.repl.co/). If it does, please report it [there](https://github.com/replit/codemirror-vim) and not here.

I don't know how to check it in it. I try to type `surround [[  ]]` in command line not work.

- [x] I'm reasonably sure that this bug is indeed about the Vimrc file support and not a general Vim in Obsidian issue. If it's a general Vim issue, report it [here](https://forum.obsidian.md/c/bug-reports/7).

**Describe the bug:**
here is my part of vimrc file
```
exmap wiki surround [[ ]]
map <A-l> :wiki 
```

Put cursor on the word "print" and press <a-l> you will get the message as the image: 
![image](https://user-images.githubusercontent.com/11295355/198288736-a0d88ae8-9617-4690-adc4-1ec2e9a0d17d.png)

**Environment (please complete the following information):**
Ubuntu 22

 - OS:
 - Vimrc plugin version: 0.6.1

**Comment by huyz** [comment]
Weird, I can't reproduce on macOS

**Comment by woshichuanqilz** [comment]
is ok now. I don't know why ...
