### ISSUE TITLE
Shift key not mapping

### ISSUE THREAD

**Issue by tjex** [esm7/obsidian-vimrc-support#143]
**Please Review Before Posting!**

- [ x ] I checked that the bug *does not happen* in the [CodeMirror Vim demo](https://codemirror-vim--util.repl.co/). If it does, please report it [there](https://github.com/replit/codemirror-vim) and not here.
- [ x ] I'm reasonably sure that this bug is indeed about the Vimrc file support and not a general Vim in Obsidian issue. If it's a general Vim issue, report it [here](https://forum.obsidian.md/c/bug-reports/7).

**Describe the bug:**
Remapping `<S-h>` does not overwrite regular vim behavior. 

**To Reproduce:**

0. disable obsidian hotkey binding for navigate back / forward
1. add this to obsidian vimrc:
```
exmap back obcommand app:go-back
nmap <S-h> :back
exmap forward obcommand app:go-forward
nmap <S-l> :forward
```
2. restart osidian. 
3. open a note with internal links
4. open some internal links to create view history
5. try shortcuts from step 1

For me, the cursor still jumps to top / bottom of page.

**Environment (please complete the following information):**

 - OS: OSX 12.6
 - Vimrc plugin version: 0.7.3

**Additional context:**

The keymap works if replacing `<S-h>` with `<C-h>`.   
I might be missing some technical detail about mapping the shift key (instead of control) / not understanding the different map functions `nmap`, `imap`, etc.
Apologies in advance if I am, but I did read the documentation and didn't find anything specific. 
I have mapped the shift key in regular vim, but have specified that it is only active in normal mode. Perhaps this issue it lies therein.

I've also seen in issue https://github.com/esm7/obsidian-vimrc-support/issues/48 that the user was mapping the shift key just fine, and used the same syntax as above.

**Comment by jiyee** [comment]
`exmap back obcommand app:go-back
nmap H :back
exmap forward obcommand app:go-forward
nmap L :forward`

it works.

**Comment by tjex** [comment]
quite right! thank you.
