### ISSUE TITLE
`imap jk <ESC>` not work.

### ISSUE THREAD

**Issue by woshichuanqilz** [esm7/obsidian-vimrc-support#148]
`imap jk <ESC>` not work. After you type "jk",  j and k disappear, and still in the insert mode. 
And I check  the console nothing related print out. How to fix it?

**Comment by philipjin** [comment]
+ 1 , same issue.  obsidian v1.0.3 , latest plugin version

**Comment by Jeremiah-Roise** [comment]
for any future visitors changing the remap from `imap jk <ESC>` to `imap jk <Esc>` fixes the issue.
[credit for this solution.](https://github.com/esm7/obsidian-vimrc-support/discussions/61)

**Comment by woshichuanqilz** [comment]
> for any future visitors changing the remap from `imap jk <ESC>` to `imap jk <Esc>` fixes the issue. [credit for this solution.](https://github.com/esm7/obsidian-vimrc-support/discussions/61)

What is the difference here?

**Comment by Jeremiah-Roise** [comment]
#

> > for any future visitors changing the remap from `imap jk <ESC>` to `imap jk <Esc>` fixes the issue. [credit for this solution.](https://github.com/esm7/obsidian-vimrc-support/discussions/61)
> 
> What is the difference here?

the the `sc` is lowercase in the second example.

**Comment by yedamao** [comment]
> for any future visitors changing the remap from `imap jk <ESC>` to `imap jk <Esc>` fixes the issue. [credit for this solution.](https://github.com/esm7/obsidian-vimrc-support/discussions/61)

It works. Thank u
