### ISSUE TITLE
Feature Request: specific VIMRC_FILE_NAME

### ISSUE THREAD

**Issue by tadashi-aikawa** [esm7/obsidian-vimrc-support#15]
Hi.

Thank you for your great plugin!

I have been managing my vault on Box. (of course, includes .obsidian.vimrc)
But [it can't seem to sync dotfiles both on Box Sync and Box Drive.](https://support.box.com/hc/en-us/articles/360044195433-File-Types-Ignored-or-Blocked-by-Box-Sync-and-Box-Drive)

Although it seems to work if I overwrite `.obsidian.vimrc` within [main.ts#L13](https://github.com/esm7/obsidian-vimrc-support/blob/master/main.ts#L13), it would be nice if we can specify `VIMRC_FILE_NAME` on PLUGIN OPTIONS so that Box doesn't ignore it.

Best regards.

**Comment by esm7** [comment]
Sorry for the long time to reply.
Looking forward to using Obsidian on multiple devices, I think this is an important feature to implement. I'll try to get around to it when I have a few hours to work on the plugin.
