### ISSUE TITLE
Noremap doesn't work as expected

### ISSUE THREAD

**Issue by Smogious** [esm7/obsidian-vimrc-support#150]
I tried to switch j and gj (as well as k and gk) with:
```
noremap j gj
noremap gj j
```
However this causes both j and gj to act like j, and putting the lines the other way around causes both of them to act like gj, so it seems that it's still recursively mapping. I'm fairly new to vim so I may be doing something wrong, but I'm pretty sure this should switch them with how `noremap` is supposed to work.

**Environment:**

 - OS: Windows 10
 - Vimrc plugin version: 0.8.0

**Comment by RiccardoTonioloDev** [comment]
Hey it seems like the `.obsidian.vimrc` doesn't like the `noremap` as a command. Try to use `imap` instead.
Example: `imap j gj`

**Comment by Smogious** [comment]
@RiccardoTonioloDev wouldn't imap just map it for insert mode? That's the one mode I don't want this mapping for and I don't see how that would give the noremap functionality to switch 2 commands.

**Comment by RiccardoTonioloDev** [comment]
`imap` let's you map a shortcut to another. For example I'm using `imap jk <Esc>`: it allows me to press jk (in insert mode) and having the same effect as pressing <Esc> (going into normal mode).

**Comment by Smogious** [comment]
@RiccardoTonioloDev I know, I have that same `jk` mapping, but I don't see how that's relevant to my problem. As I said, I don't want this mapping for insert mode so I wouldn't use `imap`, and if I used non-recursive mappings for this it wouldn't work since I'm trying to map 2 shortcuts to each other. I thought recursive mappings would solve this but it seems to be behaving the same as non-recursive mappings.

**Comment by hjm7** [comment]
I know that you want to want to switch logical line and visual line, I use
```
noremap j gj
noremap gj j
```
work well, it is non-recursively. My environment is win 11 and plugin 0.8.0.

**Comment by Smogious** [comment]
@hjm7 I just tried it again and it seems to work now, I guess it was fixed in an update (or I was just doing something wrong before).
