### ISSUE TITLE
Yank to system clipboard no longer works

### ISSUE THREAD

**Issue by krusse** [esm7/obsidian-vimrc-support#156]
Yank to system clipboard no longer works.

**To Reproduce:**
yy

**Environment (please complete the following information):**

 - OS: Windows 11
 - Vimrc plugin version: 0.8.0

**Additional context:**

I still have `set clipboard=unnamed` in my .obsidian.vimrc, but I see that was recently [deprecated](https://github.com/esm7/obsidian-vimrc-support/pull/107). I don't see "a settings toggle" in the plugin settings as it says in that PR:
![image](https://user-images.githubusercontent.com/6863901/209173915-f57ab126-b914-4603-8f1a-d09e35f72db2.png)

Bug or am I missing something?

**Comment by krusse** [comment]
I solved it by adding `unmap <C-c>` into my .vimrc.

It is a bit of a mystery why I have never had to do this before. Anyway, solved.

**Comment by jottr** [comment]
How is this solved by adding `unmap <C-c>`?  
If this solves the clipboard behavior somehow, then please add this to the [relevant section](https://github.com/esm7/obsidian-vimrc-support/blob/ba94e13835d079b4d83eaa178dd264cf74d6a23f/README.md?plain=1#L43-L44. ) in the README. 

The README still suggests the following: 
```
" Yank to system clipboard
set clipboard=unnamed**
```

**Comment by jottr** [comment]
Yeah,, the `**` was a pasting error. Sorry about that. Fixed the original post. 
It seems that the plugin never worked for me, because I fell into this trap too: https://github.com/esm7/obsidian-vimrc-support/issues/241
