### ISSUE TITLE
'imap jk <esc>'  doesn't work

### ISSUE THREAD

**Issue by yuanczx** [esm7/obsidian-vimrc-support#158]
**Describe the bug:**

I hava only `imap jk <esc>` in my `.obsidian.vimrc` file and restart Obsidian. 
I type `jk` on insert mode but  it doesn't return to normal mode

**Environment**

 - OS: Windows11 22H2
 - Vimrc plugin version: 0.8.0

**Comment by rpast** [comment]
Hey @yuanczx write _<Esc>_ capitalized

`imap jk <Esc>`

**Comment by yuanczx** [comment]
It works thanks
