### ISSUE TITLE
nmap <Space><Space> writes a '.' to the note

### ISSUE THREAD

**Issue by msanjaq** [esm7/obsidian-vimrc-support#160]
**Please Review Before Posting!**

- [X] I checked that the bug *does not happen* in the [CodeMirror Vim demo](https://codemirror-vim--util.repl.co/). If it does, please report it [there](https://github.com/replit/codemirror-vim) and not here.
- [X] I'm reasonably sure that this bug is indeed about the Vimrc file support and not a general Vim in Obsidian issue. If it's a general Vim issue, report it [here](https://forum.obsidian.md/c/bug-reports/7).

**Describe the bug:**

Using nmap on `<Space><Space>` inserts a `.` in the editor.

Example .obsidian.vimrc

```
unmap <Space>
nmap <Space><Space> i
```

This bug only happens when I've recently typed something while in `Insert Mode` and then immediately invoke `<Space><Space>` in `Normal Mode`. Perhaps there is a race condition? See video below.

https://user-images.githubusercontent.com/19857160/210426375-41cf73a8-b590-4ebb-8576-f34dcade4555.mov

I am fairly certain this is NOT a CodeMirror issue. I created the same mapping in repl and I could not reproduce this behavior. See my [custom repl](https://replit.com/@msanjaq/codemirror-vim-debug-space-issue#dev/index.ts).

**To Reproduce:**
1. Load the above .obsidian.vimrc
2. Enter insert mode
3. Insert any text (e.g. `aaa`)
4. Enter normal mode
5. Press `<Space><Space>` 
6. The text will be modified into `aa.`

**Environment (please complete the following information):**

 - OS: macOS Monterey 12.6
 - Vimrc plugin version: 0.8.0

**Additional context:**

This bug appears with ANY normal mapping to `<Space><Space>`. For example, my goal is to mimic spacemacs and map `<Space><Space>` to the command pallete. 

```
unmap <Space>
exmap searchCommands obcommand command-palette:open
nmap <Space><Space> :searchCommands
```

The same bug occurs.

**Comment by msanjaq** [comment]
Turns out the issue is with macOS. You must disable `Add period with double-space` on the keyboard settings:

<img width="667" alt="image" src="https://user-images.githubusercontent.com/19857160/210582152-ef613b8f-9d76-4c5c-b8f7-43f1a4a0e265.png">

**Comment by jiyee** [comment]
sad:(
