### ISSUE TITLE
Can't map chords with enter/return (CR)

### ISSUE THREAD

**Issue by aikinai** [esm7/obsidian-vimrc-support#165]
**Please Review Before Posting!**

- [x] I checked that the bug *does not happen* in the [CodeMirror Vim demo](https://codemirror-vim--util.repl.co/). If it does, please report it [there](https://github.com/replit/codemirror-vim) and not here.
- [x] I'm reasonably sure that this bug is indeed about the Vimrc file support and not a general Vim in Obsidian issue. If it's a general Vim issue, report it [here](https://forum.obsidian.md/c/bug-reports/7).

**Describe the bug:**

It seems that any keybindings that use enter/return (`cr` in normal Vim) don't work. In particular, I'm trying to map shift-enter, but I also can't get enter to work with other modifiers either.

**To Reproduce:**

- Add `imap <S-cr> <Esc>` to `.obsidian.vimrc`
- Restart Obsidian
- Open a note and press `i` to change to insert mode
- Press shift-enter
- It does not trigger escape, but should

This works in normal Vim. I also tried a few things to experiment. I tested `<S-CR>` (capitalized), `<C-cr>` (control), etc. and couldn't get it to work with anything, so I assume it's support for enter/return that is missing rather than something wrong with the shift  modifier. Though I did find #143 where you recommended capital letters in the map rather than a shift modifier, but there's no capital version of enter that I can include in the keybinding.

**Environment (please complete the following information):**

 - OS: MacOS 13.1
 - Vimrc plugin version: 0.9.0

**Comment by jiyee** [comment]
It works in my environment, add `imap <S-CR> <Esc>` to `.obsidian.vimrc`

**Comment by aikinai** [comment]
Oh, it is working now! I experimented so many times and even saw it working with other chords, so I'm not sure how I missed it. Anyway, all good now; sorry for the noise!
