### ISSUE TITLE
Mapping C-w

### ISSUE THREAD

**Issue by p-kolacz** [esm7/obsidian-vimrc-support#17]
Can you map `<c-w>s` and `<c-w>v` to open horizontal and vertical splits?

**Comment by esm7** [comment]
This can be generalized to an idea of exposing Obsidian commands to Ex commands that can be mapped. It sounds useful and I'll look into it.

**Comment by lyndhurst** [comment]
I am just digging into the whole vim mode functionality, so I am no expert, and I do not know if [VsCodeVim](https://github.com/VSCodeVim/Vim#key-remapping) is based on CodeMirror as well, but as I am setting it up in VsCode, I find that binding native VsCode commands to vim-mode really is a great addition.
Thanks for taking the time to look into it :+1:

**Comment by esm7** [comment]
I just released version 3.0 of the plugin which introduces an `obcommand` Ex command that can do what you wanted (`obcommand workspace:split-vertical`).
I'm not sure that specifically `C-wv` will work with the CodeMirror limitations, but even if not, you can find another combination that will!

**Comment by lyndhurst** [comment]
@ingshtrom , I have not been using Obsidian in a while, I finally went back to vimwiki so I cannot easily test it right away. All I can tell you from the notes I took right after the feature was released, is that I specifically could not get `<C-w>` to work. I did manage to successfully bind some `obcommand` though like the following example: 

```
exmap back obcommand app:go-back
nmap <C-o>b :back<Cr>
```

From my notes, `<C-o>` is the only one I can be sure I got working, and `<C-w>` the only one failing consistently. I do not have any records of other combinations I might have tried unfortunately. Sorry, that is all I got, hope it helps anyway.

**Comment by esm7** [comment]
I'm not quite sure why, but some mappings work with CodeMirror and some don't. For example I believe you will find that `nmap <C-z>l :focusRight` works fine, yet as you've seen `<C-w>l` consistently fails. It might be related to Obsidian default mappings being caught and not transmitted to CodeMirror (even if they are not mapped to anything), or maybe something completely else.

**Comment by ingshtrom** [comment]
Very weird. I quite like `<c-w>`. Oh well, I'll play around some more and maybe train my brain to use a different key combination. Thank you both for the quick response!

**Comment by lyndhurst** [comment]
@ingshtrom , if you do more testing, maybe have a look at the [CodeMirror source code](https://github.com/codemirror/CodeMirror/blob/master/keymap/vim.js) if you did not already. You can easily spot the default key combinations that comes with it, `<C-w>` being one of them.
There is a `//ignore C-w in normal mode` comment l.158 that might be the reason the plugin cannot override it. By trying a few of them, you might identify a pattern to find out the available keybindings you can map.
Good luck.

**Comment by pmbauer** [comment]
soooo ... https://github.com/esm7/obsidian-vimrc-support/issues/67#issuecomment-1063734459

**Comment by pmbauer** [comment]
@p-kolacz 

> [!INFO]
> As of [[2022-03-14]], release 0.14.0, this hack is no longer needed. [[licat]] modified the included `vim.js` so `C-w` leader shortcuts are supported natively.
> 
> To enable vim-native `C-w` window manipulation.
> 
> 1. Make sure the `Ctrl-W` hotkey is removed for `Open Settings / Hotkeys > Close active pane`
> 2. Install the [obsidian-vimrc-support plugin](obsidian://show-plugin?id=obsidian-vimrc-support).
> 3. Add the following to `<VAULT_ROOT>/.obsidian.vimrc`

 ```
 " window controls
 exmap wq obcommand workspace:close
 exmap q obcommand workspace:close
 
 exmap focusRight obcommand editor:focus-right
 nmap <C-w>l :focusRight
 
 exmap focusLeft obcommand editor:focus-left
 nmap <C-w>h :focusLeft
 
 exmap focusTop obcommand editor:focus-top
 nmap <C-w>k :focusTop
 
 exmap focusBottom obcommand editor:focus-bottom
 nmap <C-w>j :focusBottom
 
 exmap splitVertical obcommand workspace:split-vertical
 nmap <C-w>v :splitVertical
 
 exmap splitHorizontal obcommand workspace:split-horizontal
 nmap <C-w>s :splitHorizontal
 ```
