### ISSUE TITLE
Add Select Between functionality

### ISSUE THREAD

**Issue by ChrisBarfod** [esm7/obsidian-vimrc-support#170]
Being able to select text inside quotes or asterisks, etc. would come in really handy. 

Like the vim command `vi"` to select inside double quotes.

**Comment by jiyee** [comment]
select text inside quotes and brackets is already supported，`vi"` and `vi)`，but select text inside asterisks is not supported.

**Comment by ChrisBarfod** [comment]
Ah yes, the Smart Typography plugin was interfering with the quotes.
