### ISSUE TITLE
Symlinks and sourcing from another file

### ISSUE THREAD

**Issue by jsrozner** [esm7/obsidian-vimrc-support#188]
**Describe the feature that you'd like:**
I manage my dotfiles using git in a centralized repo. I want to be able to symlink from my central repo to the obsidian vault, but it looks like this plugin does not support loading symlink? 

For example 
`ln -s ~/.dotfiles/.vimrc.obsidian ~/obsidian_vault/.obsidian.vimrc`

**A clear and concise description of what you want to happen.**
- I would like .obsidian.vimrc to still work if it is a symlink and not a file

- Additionally it looks like the command
`source <other file>` is not supported from within the obsidian vimrc

**Comment by oskarryn** [comment]
If works with a symlink for me. Did you restart Obsidian after creating the symlink?

**Comment by jsrozner** [comment]
Sorry for the delay. 
I think my symlink setup somehow had a bug. I am not sure exactly why (`ln -s` would succeed but the alias was immediately broken). It works now!

But I want to confirm that having something like
`source <path_to_another_file>` in the obsidian vim file is not supported?

**Comment by jsrozner** [comment]
The line involved is [here](https://github.com/esm7/obsidian-vimrc-support/blob/master/main.ts#L670).
I guess it makes sense we cannot source from outside the vault: how would we read from another file.

Solution is to set up my symlinks to link both files to the vault and then source from within the vault.
