### ISSUE TITLE
Leader key support?

### ISSUE THREAD

**Issue by romariorobby** [esm7/obsidian-vimrc-support#19]
is it possible to implement leaderkey ?

**Comment by esm7** [comment]
It's doable, but will require to parse existing map commands ahead of CodeMirror (because we would want that regular `map` will work too, and the plugin doesn't handle that).
I'm not sure I can get around to work on that soon enough, but would love contributions to the code!

**Comment by datavistics** [comment]
There might be some other ways:
https://discuss.codemirror.net/t/possible-vim-leader-key-work-around/3006/4

**Comment by esm7** [comment]
That's not a workaround for supporting "proper" leader key setups, but I guess it's definitely useful for some use cases. I don't have an idea how to incorporate this to the plugin in a reasonably generic way though.
