### ISSUE TITLE
<Esc> imap don't work

### ISSUE THREAD

**Issue by Nagi-ovo** [esm7/obsidian-vimrc-support#192]
This bug doesn't appear in code mirror, but happens in my Obsidian Vim mode.

This is my .obsidian.vimrc settings, everything works great except `imap jj`.
```
" jj instead of <Esc> sounds better for me  
imap jj <Esc> 
" semicolon as colon
nmap ; :
" Have j and k navigate visual lines rather than logical ones
nmap j gj
nmap k gk
" I like using H and Lj for beginning/end of line
nmap H ^
nmap L $

```
My environment is Windows 11
Obsidian v1.3.5

 - OS:Windows 11 
 - Obsidian: v1.3.5
 - Vimrc plugin version: 0.9.0

**Comment by Nagi-ovo** [comment]
fixed after a laptop reboot......

**Comment by tommdq** [comment]
I'm having a similar issue.. i swap j & k for normal mode and also wanted to do this for visual . This is my .obsidian.vimrc 
I've also tried 'vmap j k' but it's not working. Thank you in advanced if you know how to solve it :) 

`nmap j gk
nmap k gj
imap fj <Esc>
vmap j gk
vmap k gj`

**Comment by Nagi-ovo** [comment]
> I'm having a similar issue.. i swap j & k for normal mode and also wanted to do this for visual . This is my .obsidian.vimrc I've also tried 'vmap j k' but it's not working. Thank you in advanced if you know how to solve it :)
> 
> `nmap j gk nmap k gj imap fj <Esc> vmap j gk vmap k gj`

Try this;，perhaps it will work :)
```
nmap j gk
nmap k gj
imap fj <Esc>
vmap j gk
vmap k gj
xmap j gk
xmap k gj
```
```
