### ISSUE TITLE
Would autocompletion (ctrl-p, ctrl-n) be doable?

### ISSUE THREAD

**Issue by RhvdG** [esm7/obsidian-vimrc-support#20]
I've also entered a request with the CodeMirror project, but there doesn't seem to be anyone taking care of the Vim stuff there, so I'll just ask here, too: autocompletion would really benefit many Obsidian users, especially those who do a lot of writing in Obsidian. If it's technically doable to implement autocompletion (ctrl-p, ctrl-n), that would be great.

**Comment by esm7** [comment]
The general behavior of autocompletion doesn't exist in Obsidian AFAIK, and it's outside the scope of this little plugin :(
There seems to be an [autocomplete plugin](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin) which I was not aware of, I don't know how usable it is. But if it's good enough, perhaps it can be extended with Vim bindings!

**Comment by RhvdG** [comment]
Thanks. I found the plugin shortly after entering this issue, and it works quite well.
