### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by hongalex** [esm7/obsidian-vimrc-support#202]
**Describe the feature that you'd like:**

Was hoping to see if you were willing to add an open source license like [Apache](https://opensource.org/license/apache-2-0/) or [MIT](https://opensource.org/license/mit/)

**Comment by jwhitley** [comment]
I'll add that this is effectively a prerequisite to bringing a new maintainer on baord, since that entails a new person creating a derivative work as far as copyright law is concerned.

**Comment by esm7** [comment]
I'm all for that, just not very acquainted on the topic, and will need to learn it a bit!

**Comment by darylducharme** [comment]
+1 to adding a license as some companies, like the one I work for, only allow us to use open source tools with certain licenses.

**Comment by esm7** [comment]
Added, thanks everybody for the incentive :pray:

**Comment by hongalex** [comment]
Thanks @esm7 for adding this!
