### ISSUE TITLE
Insert Mode

### ISSUE THREAD

**Issue by whippingdot** [esm7/obsidian-vimrc-support#21]
Small question - how do you remap keys in insert mode?

**Comment by esm7** [comment]
There is an `imap` command available by default (but no `inoremap`).

**Comment by ostapkob** [comment]
in `imap` not work `<Left> <Rirgh> <BS>`
how i can use `<C-h>` how backspace

**Comment by esm7** [comment]
Please try the [CodeMirror Vim page](https://codemirror.net/demo/vim.html) to isolate Obsidian and the Vimrc plugin from the functionality that CodeMirror implements.
I want to [implement `inoremap`](https://github.com/esm7/obsidian-vimrc-support/issues/24), and this can help with some of the topics, but generally the right place to discuss these limitations is in the [CodeMirror repo](https://github.com/codemirror/CodeMirror/issues).

**Comment by ostapkob** [comment]
```
nmap j gj
nmap k gk
nmap H ^
nmap L $
nmap <F9> :nohl
imap jf <Esc>

"use it how <BS> but it work only in end word
imap <C-h> <Esc><Del>a   
" imap <C-h> <BS> not work
" imap <C-h> <Left><Del>
" imap <C-q> <Left>
set clipboard=unnamed
```

**Comment by huyz** [comment]
Hmm I can't get any sort of insert-mode mappings working with `imap`, at least not on macOS. Not even in the https://codemirror.net/demo/vim.html demo page.  I wonder how anyone is getting that to work

**Comment by afermar** [comment]
I found a workaround at least for remapping `<Left>` and `<Right>` in insert mode.
```vimscript
imap <C-h> <Esc>i
imap <C-l> <Esc>la
```

**Comment by AHeathfield** [comment]
I'm on macOS and this works for left right up and down for moving left right up and down in insert mode

```vim
imap <C-h> <Esc>i
imap <C-l> <Esc>la
imap <C-k> <Esc>ka
imap <C-j> <Esc>ja
```

**Comment by huyz** [comment]
Yes, `imap` bindings seem to work for me now.
