### ISSUE TITLE
Error 579 and 594 recurrently appearing in console  

### ISSUE THREAD

**Issue by szfkamil** [esm7/obsidian-vimrc-support#210]
Upon start-up, the following bug appears in the console. Although it seems not to inhibit functionality for me, I think it's worth reporting.

![Screenshot 2024-01-20 at 19 09 43](https://github.com/esm7/obsidian-vimrc-support/assets/82778513/3c843a50-a36a-4b6e-91cf-5abc3238d2c2)

Steps to reproduce the behaviour:

**Environment (please complete the following information):**

 - OS: Sonoma 14.2.1
 - Vimrc plugin version: 0.9.0

**Additional context:** Error `574` and 594 keep appearing back-to-back, thorough use of Obsidian without even enabling vim mode.

**Comment by esm7** [comment]
@szfkamil if the issue wasn't resolved (e.g. by finding somehow that the plugin isn't the core issue), I think we should leave it open.
I'm still hopeful someone can take over the maintenance of the plugin better than I'm able to do nowadays, and this is a serious issue that should be addressed this way or another.

**Comment by szfkamil** [comment]
> @szfkamil if the issue wasn't resolved (e.g. by finding somehow that the plugin isn't the core issue), I think we should leave it open.
> I'm still hopeful someone can take over the maintenance of the plugin better than I'm able to do nowadays, and this is a serious issue that should be addressed this way or another.

The issues was no longer occurring on my environment, hence the close. Even if someone had this issue now, I wouldn't be able to tell more than is here about the environment.
