### ISSUE TITLE
[FR]: Remove plugin console warning / checks if vim mode is not toggled in Obsidian

### ISSUE THREAD

**Issue by ianTevesAcc** [esm7/obsidian-vimrc-support#228]
- [x] I understand that if my request is about supporting some Vim feature, it probably belongs [here](https://github.com/replit/codemirror-vim).

**Remove plugin console warning / checks if vim mode is not toggled in Obsidian**
When loading Obsidian up, the vimrc support plugin creates an error in the Obsidian console every second or so, until vim mode is toggled on. 
But the thing is, I only use vim mode when writing LaTeX in Obsidian. So I don't turn it on until I need it. Therefore it creates endless error / warnings on the console and checks for vim mode to be toggled. 

It would be awesome if it only checked once and if vim mode is not toggled, it would be quiet. (At least check in the background and not fill the entire console with warnings.)

**Comment by esm7** [comment]
Fixed in the upcoming release.
