### ISSUE TITLE
`imap <c-h> <BS>` not working

### ISSUE THREAD

**Issue by kohane27** [esm7/obsidian-vimrc-support#23]
Hello there! First, thank you for this addon! It's almost perfect... except this particular issue.

The default `<c-h>` in Insert mode to delete one character on the left isn't working. So I tried to remap it with `imap <c-h> <BS>`, but it's not working either.

I've looked into [CodeMirror/keymap/vim.js](https://github.com/codemirror/CodeMirror/blob/master/keymap/vim.js) and found out that there's no default mapping for `<C-h>`, which is weird because `<C-h>` in Insert mode is the default to delete one character on the left in Vim.

Any workaround or ideas? Thanks!

**Comment by esm7** [comment]
First, Ctrl+H is mapped in Obsidian by default to Search & Replace, and I believe you need to unset that mapping from the Obsidian settings before it can be expected to work in Vim mode.
However, it seems that for some reason `<C-` mappings don't work with `imap` at all. This also happens in the [CodeMirror Vim demo](https://codemirror.net/demo/vim.html), so I think you should open them a bug about that!
