### ISSUE TITLE
How do I mimic arrow key presses with vimrc?

### ISSUE THREAD

**Issue by ianTevesAcc** [esm7/obsidian-vimrc-support#230]
- [x] I know this plugin is about *persisting changes* to the Vim support built into Obsidian, plus some bonus features, and considered asking in the [Obsidian forum](https://forum.obsidian.md/c/get-help/19) first.

How do I map `<C-h>`, `<C-j>`, `<C-k>`, `<C-l>` to `<Ctrl+LeftArrowKey>`, `<Ctrl+DownArrowKey>`, `<Ctrl+UpArrowKey>`, `<Ctrl+RightArrowKey>`?

**Comment by L7amlau** [comment]
It seems like you can't do that because the <C-h> is occupied by obsidian itself for find & replace. My solution is use the Alt key instead.
