### ISSUE TITLE
vimrc plugin unable to read/detect .obsidian.vimrc file

### ISSUE THREAD

**Issue by sbom641** [esm7/obsidian-vimrc-support#232]
**Please Review Before Posting!**

- [ ] I checked that the bug *does not happen* in the [CodeMirror Vim demo](https://codemirror-vim--util.repl.co/). If it does, please report it [there](https://github.com/replit/codemirror-vim) and not here.
- [ ] I'm reasonably sure that this bug is indeed about the Vimrc file support and not a general Vim in Obsidian issue. If it's a general Vim issue, report it [here](https://forum.obsidian.md/c/bug-reports/7).

**Describe the bug:**

I think obsidian plugin is not able to read the .obsidian.vimrc file I have created in the root directory. 
This is the error I am getting from the console 

```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'setText')
    at VimrcPlugin.updateVimStatusBar (plugin:obsidian-vimrc-support:587:27)
    at VimrcPlugin.updateVimEvents (plugin:obsidian-vimrc-support:665:22)
    at eval (plugin:obsidian-vimrc-support:625:18)
    at e.tryTrigger (app.js:1:723190)
    at e.trigger (app.js:1:723123)
    at t.trigger (app.js:1:2283688)
    at t.activeLeafEvents (app.js:1:2269215)
    at l (app.js:1:522936)
    at c (app.js:1:523052)
```

**To Reproduce:**

Steps to reproduce the behavior: Not sure  ? 

**Environment (please complete the following information):**
- Obsidian: v1.6.7
 - OS: Windows 11 22H2
 - Vimrc plugin version:  0.10.0

**Additional context:**

I wanted ctrl+d because for some reason the vim in obsidian by default is mapping ctrl + d to delete a line, while ctrl + U works as expected. 
.obsidian.vimrc contents 

```
" Map Tab to switch from insert mode to normal mode
inoremap <Tab> <Esc>

" Basic movement mappings
nnoremap <C-d> <C-d>
nnoremap <C-u> <C-u>
```

Any help would be appreciated.

**Comment by oars** [comment]
Seeing this as well.

**Comment by silicakes** [comment]
same

**Comment by esm7** [comment]
Thanks for reporting and the super helpful console error. Fixed in the new release.

**Comment by gordonn** [comment]
I'm having the same issue
