### ISSUE TITLE
Obsidian 1.7.2 or above: ex-commands cannot be triggered without `Enter`

### ISSUE THREAD

**Issue by RyotaUshio** [esm7/obsidian-vimrc-support#235]
**Please Review Before Posting!**

- [x] I checked that the bug *does not happen* in the [CodeMirror Vim demo](https://codemirror-vim--util.repl.co/). If it does, please report it [there](https://github.com/replit/codemirror-vim) and not here.
- [x] I'm reasonably sure that this bug is indeed about the Vimrc file support and not a general Vim in Obsidian issue. If it's a general Vim issue, report it [here](https://forum.obsidian.md/c/bug-reports/7).

**Describe the bug:**

In the discord channel for insiders (`#insider-desktop-release`), the Obsidian team announced that the [Obsidian 1.7.2](https://obsidian.md/changelog/2024-09-19-desktop-v1.7.2/) update has introduced a breaking change for this plugin. 

https://discord.com/channels/686053708261228577/716028884885307432/1286388714158948414

> We acknowledge that this release might break a few plugins, so we're going to do our best to track and proactively notify plugin devs of breakages.
>
> #### Known Plugin Issues/Incompatibilities
> This is a list of known plugin incompatibilities. We will be reaching out to plugin developers to help them resolve the issues. Please report any additional plugins experiencing issues with this build and we will add them to the list.
> 
> ...
> - **Vimrc** plugin breaking change. **ex-commands now require an ending <CR>.**
> 
> ...

Sorry if you are already working on this, but I didn't see an issue or commit about this so I thought I should let you know just in case.

**To Reproduce:**

Save `.obsidian.vimrc` with the following content (which is a part of the example in README):
```
exmap back obcommand app:go-back
nmap <C-o> :back
```

Before Obsidian 1.7.2, pressing `<C-o>` used to execute the command without any extra input. Now, however, `<C-o>` opens up the command line filled with `:back`, and a user has to press Enter to actually trigger the command.

As a result, currently I have to rewrite the above script to

```
exmap back obcommand app:go-back
nmap <C-o> :back<CR>
```

to ensure that my vimrc works the same as before.

Here is another example of the same problem:

Before 1.7.2:
```
" Make o and O respect context
" https://forum.obsidian.md/t/vim-o-and-o-should-respect-understand-current-context-lists/48386/15?u=ush
exmap blankBelow obcommand obsidian-editor-shortcuts:insertLineBelow
exmap blankAbove obcommand obsidian-editor-shortcuts:insertLineAbove
nmap &a& :blankAbove<CR>
nmap &b& :blankBelow<CR>
nmap o &b&i
nmap O &a&i
```

After 1.7.2:
```
" Make o and O respect context
" https://forum.obsidian.md/t/vim-o-and-o-should-respect-understand-current-context-lists/48386/15?u=ush
exmap blankBelow obcommand obsidian-editor-shortcuts:insertLineBelow
exmap blankAbove obcommand obsidian-editor-shortcuts:insertLineAbove
nmap &a& :blankAbove<CR>
nmap &b& :blankBelow<CR>
nmap o &b&i
nmap O &a&i
```

**Environment (please complete the following information):**

 - OS: macOS Ventura 13.6.6
 - Vimrc plugin version: 0.10.1

**Additional context:**

I wonder if it would fix this issue to implicitly append `<CR>` after every ex-command found in the loaded vimrc file. I'm not sure if this could cause any conflicts with other parts.

Anyway, thank you a lot for maintaining this important project for the Obsidian community.

**Comment by esm7** [comment]
Indeed, note it's documented in Obsidian's release notes, and the Vimrc README has an updated version ready for as soon as Obsidian release the version publicly. All in all it's a good change, as it adds more options for what you can do with the Vimrc!

**Comment by laxisforte** [comment]
The plugin is fantastic. It's made my work so much easier...
But now I have the same problem written above. Any guidance with this issue would be appreciated.

OS edition -> Windows 11 Pro
OS version -> 23H2
Obsidian version -> 1.7.4
Vim support plugin version -> 0.10.1

**Comment by esm7** [comment]
Just add `<CR>` at the end of mappings that start with `:`, for example `nmap <C-o> :back<CR>`.
