### ISSUE TITLE
surround: backward selection gives range error

### ISSUE THREAD

**Issue by awaken233** [esm7/obsidian-vimrc-support#236]
**Describe the bug:**

When doing a backward selection (i.e. `v`, then `b` a couple of times and then `[[`) I get the following error:

**Environment (please complete the following information):**

 - OS: macos
 - Vimrc plugin version: 0.10.1

**Additional context:**

![image](https://github.com/user-attachments/assets/b9e59c0f-b1c3-459c-b2fa-351bece3a5e2)

![image](https://github.com/user-attachments/assets/5a4e3053-ea74-4437-ad3a-5829dcfaa2eb)

**Comment by esm7** [comment]
This was already fixed (https://github.com/esm7/obsidian-vimrc-support/issues/236), but it's a good reminder that I didn't release the new version yet!
