### ISSUE TITLE
documentation clarity: not sure what VAULT_ROOT is

### ISSUE THREAD

**Issue by dbalatero** [esm7/obsidian-vimrc-support#241]
**Please Review Before Posting!**

- [x] I checked that the bug *does not happen* in the [CodeMirror Vim demo](https://codemirror-vim--util.repl.co/). If it does, please report it [there](https://github.com/replit/codemirror-vim) and not here.
- [x] I'm reasonably sure that this bug is indeed about the Vimrc file support and not a general Vim in Obsidian issue. If it's a general Vim issue, report it [here](https://forum.obsidian.md/c/bug-reports/7).

**Describe the bug:**

In the documentation, it references `VAULT_ROOT`, but I'm not sure if that refers to:

- `path/to/MyVault`
- `path/to/MyVault/.obsidian`

I could see it go either way. Can we clarify this in documentation? Currently I'm doing guess & check to see if the vimrc file is picked up.

**To Reproduce:**

Read the docs I guess!

**Environment (please complete the following information):**

 - OS: N/A
 - Vimrc plugin version: N/A

**Comment by alythobani** [comment]
You might have found this out already but yup I believe it should be `path/to/MyVault` :)

**Comment by esm7** [comment]
Fixed, sorry for the confusion.

**Comment by dbalatero** [comment]
Thank you!
