### ISSUE TITLE
Preview mode support

### ISSUE THREAD

**Issue by tami5** [esm7/obsidian-vimrc-support#26]
Hi there,

Awesome work truly, I really appreciate the tweaks done so far. 

It would be amazing if we can have the cursor in preview mode and everything else. And with i/I a/A c/C ... it would exist the preview to the regular insert mode.

**Comment by esm7** [comment]
Hey, I wish I could do that but it's far outside the scope of this plugin. Unlike the Obsidian editor, which is powered by a component (CodeMirror) that has a Vim mode and this plugin extends, the preview mode is a web component without any such capability.
Adding Vim key bindings to preview mode is similar to Chrome/Firefox addons like Vimium, and it's worth a project of its own :)
