### ISSUE TITLE
How to map obsidian command and plugin commands

### ISSUE THREAD

**Issue by tami5** [esm7/obsidian-vimrc-support#27]
Hey @esm7,

So far I'm really happy with the vimrc support, like it helped my transition from a full time vim env a bit eaiser.

I'm kinda wondering if something like mapping a key to access a builtin obsidian or plugin command is possible.

Thanks

**Comment by esm7** [comment]
That's also the best solution for https://github.com/esm7/obsidian-vimrc-support/issues/17. It's in my shortlist to implement as soon as I manage to spend a few hours on the plugin.

**Comment by tami5** [comment]
Tell me if there's something I can do to help as I plan to invest some time into improving vim support. Is there a place we chat more and exchange ideas?

**Comment by esm7** [comment]
You are extremely welcome to take any issue or idea in this repo, it can only make things here better :)
I enabled Discussions in this repo so it would be easier to exchange general ideas. Thank you!

**Comment by esm7** [comment]
Done! You now have an `obcommand` Ex command that can launch arbitrary Obsidian or other plugins' commands :sunglasses: 
(just please see the Readme for a small usage gotcha)

**Comment by tami5** [comment]
😍 😍 now that's powerful @esm7, can't wait to try it out. Thanks, report soon
