### ISSUE TITLE
Nmap doesn't send all the keys

### ISSUE THREAD

**Issue by fsondej** [esm7/obsidian-vimrc-support#28]
I'm not sure if it's the right place to ask, but I wanted to remap
```
nmap o A<Enter>
```
so that pressing `o` in some list would continue the list, but it turns out that after insert mode is entered (after `A`) no more keypresses are sent, so the `<Enter>` won't have any effect. Tried it with other things than `<Enter>`  and anything after `A` doesn't have effect.

Is there some fix or workaround?

**Comment by esm7** [comment]
I think this is a limitation of the CodeMirror Vim implementation :( I suggest asking over there: https://github.com/codemirror/CodeMirror/issues
