### ISSUE TITLE
Setting tabSize

### ISSUE THREAD

**Issue by vesan** [esm7/obsidian-vimrc-support#3]
I would love to be able to set the `tabSize` option: https://codemirror.net/doc/manual.html#option_tabSize

Do you see setting that being a feature of this plugin? Or enable to set other CodeMirror configuration options also?

**Comment by esm7** [comment]
It's seeminly not what this plugin meant to do but it's a very low-hanging
fruit. I can easily add this as a vimrc option (in a vim-compatible way)
the next time I work on the plugin, or feel free to open a PR.

**Comment by vesan** [comment]
So it would be something like this next to the clipboard option definition?

```javascript
CodeMirror.Vim.defineOption('tabstop', 4, 'number', [], (value, cm) => {
	if (value) {
		cmEditor.setOption('tabSize', value);
		console.log('Vim is now set to use tabSize ' + value);
	}
});
```

**Comment by esm7** [comment]
Yeah, seems like this would do the trick :)

**Comment by esm7** [comment]
I incorporated this into the plugin in version 0.2.1 :sunglasses:
