### ISSUE TITLE
trying to use obcommand for switcher

### ISSUE THREAD

**Issue by tami5** [esm7/obsidian-vimrc-support#31]
Hey @esm7 , I tried to map open switcher to space space, but it didn't work for me.

```
exmap switcher obcommand app:switcher:open
nmap <space><space> :switcher
```

**Comment by DannyDies** [comment]
Did you unmap space first? 
`unmap <Space>`
And seems like codemirror require Space with capital S only.

**Comment by esm7** [comment]
1. As @DannyDies noted, first `unmap <Space>` with a capital `S`.
2. Note that the command name (as printed in the Developer Console with `:obcommand` without params) is `switcher:open` (no `app:`).

Using these I was able to map double-space to the switcher.

**Comment by tami5** [comment]
Oh it did work. Thanks a lot guys !

**Comment by meijieru** [comment]
I have the following setting which doesn't work

```
unmap <Space>
exmap openSwitcher obcommand switcher:open
nmap <Space>f openSwitcher
```

Do you have any idea?
