### ISSUE TITLE
Move clipboard setting to settings page?

### ISSUE THREAD

**Issue by Andr3wD** [esm7/obsidian-vimrc-support#36]
The clipboard setting would likely do better inside the settings page instead of inside the `.obsidian.vimrc` file.

**Comment by esm7** [comment]
The idea was to put it in `.obsidian.vimrc` because that's the most Vim-compatible way (i.e. that's the same setting I have in my desktop `.vimrc` file).
The way I see it, the settings pane for the plugin is only for things that don't have a standard Vim setting.

**Comment by Andr3wD** [comment]
Oh, my bad. I'm not too familiar with vim configs. The clipboard setting is fine as is then.
