### ISSUE TITLE
Unable to use space chords

### ISSUE THREAD

**Issue by jaideeprana** [esm7/obsidian-vimrc-support#49]
I tried to follow the documentation and thought of using <space> v for vertically splitting the editor but no luck.

Any idea what I could be doing wrong?

Here's my config file:

```
" Have j and k navigate visual lines rather than logical ones
nmap j gj
nmap k gk
" I like using H and L for beginning/end of line
nmap H ^
nmap L $
" Quickly remove search highlights
nmap <F9> :nohl

" Yank to system clipboard
set clipboard=unnamed

unmap <Space>
nmap <Space>v :obcommand workspace:split-vertical
```

**Comment by Andr3wD** [comment]
Please see https://github.com/esm7/obsidian-vimrc-support#mapping-obsidian-commands-within-vim for help.
The README order was messed up by a recent PR I made, so this should have been right under the obcommand section. 
I've made a new PR to fix the issue, but for now the above link should work fine.

**Comment by esm7** [comment]
@jaideeprana the method described in the documentation, right where @Andr3wD linked, should solve your issue (you can't `nmap` to a command with params, so there's `exmap` as a work-around). Please comment or reopen if there's still an issue.
