### ISSUE TITLE
Feature Request: iabbrev support

### ISSUE THREAD

**Issue by JamesHWade** [esm7/obsidian-vimrc-support#5]
Thank you for this *fantastic* plugin. It makes editing in Obsidian an even better experience.

I am trying to add text expander features to Obsidian through the .obsidian.vimrc file. Is it possible you use `iabbrev`? My initial attempts were unsuccessful.

An example to create a prompt template with [Obsidian_to_Anki](https://github.com/Pseudonium/Obsidian_to_Anki/wiki/Technical):
`iabbrev zpb START<cr>Basic<cr>Front:<cr>Back:<cr>Tags: #AnkiTag<cr>END`

**Comment by esm7** [comment]
Unfortunately CodeMirror doesn't implement the Vim `iabbrev` command.
It's possible to implement it as a custom command, but although I'd love everything to be in a vimrc file, perhaps you should first check out the Obsidian [text expand plugin](https://github.com/mrjackphil/obsidian-text-expand).

**Comment by JamesHWade** [comment]
Thanks for the pointer to text expand plugin. I'll stick with editing notes in Vim in the terminal for now. I agree with everything being in vimrc. Good thought.
