### ISSUE TITLE
Use <C-x><C-v><C-z>similar key in normal mode

### ISSUE THREAD

**Issue by imhgy** [esm7/obsidian-vimrc-support#51]
Is there any way that let me use `<C-x>`, `<C-v>`, `<C-z>` similar key in normal or visible mode to implement cut, paste, undo functions?

I tried `unmap <C-x>` but it did not work.

**Comment by Andr3wD** [comment]
This should do what you want:
```
vmap <C-x> d
nmap <C-x> dd
map <C-v> p
map <C-z> u
```

**Comment by imhgy** [comment]
> This should do what you want:
> 
> ```
> vmap <C-x> d
> nmap <C-x> dd
> map <C-v> p
> map <C-z> u
> ```


sure, it's an effective way to map these functions to vim statements, but is there any way to implement the original copy, paste, undo, etc. function of obsidian in normal or visible mode? Just like Pycharm, there is an option that lets you choose which handler you want to use, IDE or Vim.

**Comment by Andr3wD** [comment]
> > This should do what you want:
> > ```
> > vmap <C-x> d
> > nmap <C-x> dd
> > map <C-v> p
> > map <C-z> u
> > ```
> 
> sure, it's an effective way to map these functions to vim statements, but is there any way to implement the original copy, paste, undo, etc. function of obsidian in normal or visible mode? Just like Pycharm, there is an option that lets you choose which handler you want to use, IDE or Vim.

From my experience, it's the same thing. You can even sync the clipboard to the system clipboard with https://github.com/esm7/obsidian-vimrc-support#supported-commands `set clipboard=unnamed`.

Is there something I'm missing? What would changing the handler give you that this plugin doesn't currently have?
Also, I don't think there's any way to get around CodeMirror.Vim to allow the original handler, just from the top of my head.

**Comment by esm7** [comment]
There could potentially be an Obsidian `editor:copy` command that could be mapped with `obcommand`, but seems like Obsidian didn't export this functionality as a command. But like @Andr3wD wrote, with `set clipboard=unnamed` this should work the same. Same goes for undo.
If there is a notable functionality difference between the Vim one and the Obsidian one, it would be interesting to know and consider it as a feature request.
