### ISSUE TITLE
The functional requirements

### ISSUE THREAD

**Issue by liang-0131** [esm7/obsidian-vimrc-support#52]
`imap ,b **** <++><Esc>F*hi`
The **** <++> here is invalid

**Comment by liang-0131** [comment]
> `imap ,b **** <++><Esc>F*hi` 这里的****<++>无效

I need this
`imap jk 1234<Esc>`
`imap <key> <text><key>`
The text is now invalid. I want to know how to insert text.

**Comment by coder-user** [comment]
> > `imap ,b **** <++><Esc>F*hi` 这里的****<++>无效
> 
> I need this `imap jk 1234<Esc>` `imap <key> <text><key>` The text is now invalid. I want to know how to insert text.

Did you implement it?

**Comment by coder-user** [comment]
Did you implement it?
