### ISSUE TITLE
Feature Request: support imselect

### ISSUE THREAD

**Issue by Jackiexiao** [esm7/obsidian-vimrc-support#6]
Hi, thx for creating this wonderful plugin, it let me reconsider using obsidian instead of vscode again, but there is one more problem for me, I use Chinese to write notes so I need to switch from English and Chinese a lot, 

in vscode, I use neovim + im-select to automatically switch to English input method when I enter Normal mode. Could you support it ? 

https://github.com/daipeihust/im-select

**Comment by Jackiexiao** [comment]
ok... one more thing,  any idea about how to use `gd` command to go to `[[link]]` instead of using mouse?

**Comment by esm7** [comment]
This is actually something I want to solve since day 1!
How are you gluing the pieces together with Neovim? Do you have an autocmd to call `im-select` when switching to normal mode?

**Comment by Jackiexiao** [comment]
vscode, I set
```
autocmd InsertLeave * :silent :! C:\\im-select\\im-select.exe 1033
set clipboard+=unnamedplus
```
in `init.vim`

1033 is the code of English input method

**Comment by Jackiexiao** [comment]
I try to set
```
inoremap <Esc> <Esc><A-S>
```
<A-S> Alt + shift to switch input method, but it didn't work, any idea?

**Comment by Jackiexiao** [comment]
I manage to solve this problem by `autohotkey`, it works both in vscode and obsidian, but it's a bit complicated

In windows 10, open `Advanced keyboard options`

![image](https://user-images.githubusercontent.com/18050469/101495489-952ae180-39a3-11eb-9e03-d886ff00ce54.png)


```filename: vim-switch.ahk
$Esc::
Send, !+8
^Esc::
Send, {Esc}
return
```
 `!+8` means `Alt + Shift + 8`, so when I press down `Esc`, it send `Alt + Shift + 8` to switch to English input method
