### ISSUE TITLE
CodeMirror 6 support

### ISSUE THREAD

**Issue by lishid** [esm7/obsidian-vimrc-support#66]
The latest insider now comes with experimental Vim mode support for CodeMirror 6. You can find the alternative CodeMirror "adapter" for CodeMirror 6 at `window.CodeMirrorAdapter` (undocumented). Should be able to access a copy of the Vim object at `CodeMirrorAdapter.Vim`.

I'm not sure how much work it'll be to update this plugin but hopefully that helps with the integration.

**Comment by esm7** [comment]
That's great news! I'll work in the upcoming week on updating the plugin.

**Comment by blairfrandeen** [comment]
I noticed that the plugin seems to stop working with the latest insider build (0.13.10) - is this the same issue?

**Comment by esm7** [comment]
It should still work if you use the legacy editor (CM5) in the settings. But if you switched to the new editor, the plugin indeed stops working.
I already have a tweaked version that works with the new editor and been using it in the past days, but there's still an issue or two to solve, hopefully I'll manage to work on it today.

**Comment by esm7** [comment]
Sorry everybody for the delay, like I mentioned in the Readme, the CM6 updated landed on a couple of weeks where I have almost zero free time :(
There are still a few pieces of the plugin's functionality that I haven't yet been able to get to work under CM6, but since I don't wanna keep users waiting without a solution, I went ahead and released 0.5.0 which covers 90%. I'll do my best to find the time to complete the missing pieces (most notably `surround` and `cmcommand`) soon enough.

**Comment by tadashi-aikawa** [comment]
`set clipboard=unnamed` worked correctly! awesome! Thank you for your great work! 😆

**Comment by ereduled** [comment]
Sorry for commenting on a long closed issue.

I'm trying to add the following snippet to my `.obsidian.vimrc`
```vim
nunmap o
exmap newLine cmcommand cursorLineBoundaryForward
exmap addNewLine cmcommand insertNewlineAndIndent
nmap o :newLine :addNewLine
```
I was unable to determine whether `cmcommand` is expected to work currently or not.

The changelog (and this issue) seem to indicate that `cmcommand` is not expected to work.

My own experience is that `cmcommand` is not working
<img width="668" alt="image" src="https://github.com/esm7/obsidian-vimrc-support/assets/25099244/fa525444-2b0c-4bd9-b701-71186d80311c">


However the docs seem to indicate that it is expected to work. 
```
- cmcommand - execute arbitrary CodeMirror commands, see details below.
```

There are no `details below` in the documentation.

I believe this is something that fell between the cracks during the CM6 migration?

As an end user, how do I get cmcommand working in Obsidian today?

I apologise if this is the wrong place to ask this and if I should open a new issue.

Thanks
