### ISSUE TITLE
<C-w><key> bind not working

### ISSUE THREAD

**Issue by yarinm** [esm7/obsidian-vimrc-support#67]
I'm trying to bind the following:
```
exmap focusleft :obcommand editor:focus-left
nmap <C-w>h :focusleft
```

But when I'm doing ctrl+w, h nothing happens.

If I change the bind from C-w to <Space> or some other key that doesn't involve the control key it seems to work.

**Comment by yarinm** [comment]
@esm7 any idea why it doesn't work? This specific combination just being ignored

**Comment by pBorak** [comment]
@yarinm There was a similar thread related to this issue https://github.com/esm7/obsidian-vimrc-support/issues/17

**Comment by twio142** [comment]
Hi, are you sure the command `:obcommand editor:focus-left` works? Nothing happens when I enter it...

**Comment by esm7** [comment]
@twio142 it's probably among the many things that broke in the new editor switch and I was unable to get to fix yet.
I'll work on as many of them this week, but can you open a separate issue so this won't get lost?

**Comment by esm7** [comment]
@yarinm please see https://github.com/esm7/obsidian-vimrc-support/issues/17 as pBorak mentioned. Unfortunately it's a CodeMirror limitation that's beyond the reach of this plugin, and you'll to work around it by choosing <C-w> combinations that do happen to work or just choose other keys :(

**Comment by pmbauer** [comment]
I've no idea if upstream will accept a patch but ... not having `<C-w>` commands has been a bit of a drag.  So here is my hack (works on Mac OS, will need modified for other platforms).

```bash
TARGET_ASAR=/Applications/Obsidian.app/Contents/Resources/obsidian.asar
TMP_ASAR=/tmp/obsidian.asar
UNPACKED_ASAR=/tmp/obsidian.asar.unpacked
TARGET_VIMJS=$UNPACKED_ASAR/lib/codemirror/vim.js

# cleanup
rm -rf $TMP_ASAR $UNPACKED_ASAR

npx asar extract $TARGET_ASAR /tmp/obsidian.asar.unpacked

# DOS->unix
sed -i s/$'\r'$// $TARGET_VIMJS

cat <<EOF | patch $TARGET_VIMJS
--- vim.js	2022-03-10 00:54:21.000000000 -0500
+++ vim.patched.js	2022-03-10 01:02:05.000000000 -0500
@@ -183,7 +183,7 @@
     { keys: '<C-u>', type: 'operatorMotion', operator: 'delete', motion: 'moveToStartOfLine', context: 'insert' },
     { keys: '<C-w>', type: 'operatorMotion', operator: 'delete', motion: 'moveByWords', motionArgs: { forward: false, wordEnd: false }, context: 'insert' },
     //ignore C-w in normal mode
-    { keys: '<C-w>', type: 'idle', context: 'normal' },
+    //{ keys: '<C-w>', type: 'idle', context: 'normal' },
     // Actions
     { keys: '<C-i>', type: 'action', action: 'jumpListWalk', actionArgs: { forward: true }},
     { keys: '<C-o>', type: 'action', action: 'jumpListWalk', actionArgs: { forward: false }},
EOF

npx asar pack $UNPACKED_ASAR $TMP_ASAR

# replace with patched asar
pkill Obsidian
cp $TMP_ASAR $TARGET_ASAR

# also, update the cache
CACHE_DIR="/Users/$USER/Library/Application Support/obsidian"
LATEST_IN_CACHE=$(ls -r "$CACHE_DIR"/obsidian-*.asar | head -n 1)
cp $TMP_ASAR "$LATEST_IN_CACHE"
```

And then in my `.obsidian.vimrc`
```
exmap focusRight obcommand editor:focus-right
nmap <C-w>l :focusRight

exmap focusLeft obcommand editor:focus-left
nmap <C-w>h :focusLeft

exmap focusTop obcommand editor:focus-top
nmap <C-w>k :focusTop

exmap focusBottom obcommand editor:focus-bottom
nmap <C-w>j :focusBottom

exmap splitVertical obcommand workspace:split-vertical
nmap <C-w>v :splitVertical

exmap splitHorizontal obcommand workspace:split-horizontal
nmap <C-w>s :splitHorizontal
```

**Comment by pmbauer** [comment]
@esm7 @yarinm FYI

> [!INFO]
> As of [[2022-03-14]], release 0.14.0, this hack is no longer needed. [[licat]] modified the included `vim.js` so `C-w` leader shortcuts are supported natively.
> 
> To enable vim-native `C-w` window manipulation.
> 
> 1. Make sure the `Ctrl-W` hotkey is removed for `Open Settings / Hotkeys > Close active pane`
> 2. Install the [obsidian-vimrc-support plugin](obsidian://show-plugin?id=obsidian-vimrc-support).
> 3. Add the following to `<VAULT_ROOT>/.obsidian.vimrc`

 ```
 " window controls
 exmap wq obcommand workspace:close
 exmap q obcommand workspace:close
 
 exmap focusRight obcommand editor:focus-right
 nmap <C-w>l :focusRight
 
 exmap focusLeft obcommand editor:focus-left
 nmap <C-w>h :focusLeft
 
 exmap focusTop obcommand editor:focus-top
 nmap <C-w>k :focusTop
 
 exmap focusBottom obcommand editor:focus-bottom
 nmap <C-w>j :focusBottom
 
 exmap splitVertical obcommand workspace:split-vertical
 nmap <C-w>v :splitVertical
 
 exmap splitHorizontal obcommand workspace:split-horizontal
 nmap <C-w>s :splitHorizontal
 ```
