### ISSUE TITLE
Obsidian's New Live Preview Editor Compatibility

### ISSUE THREAD

**Issue by santiyounger** [esm7/obsidian-vimrc-support#69]
Hey, not sure if someone else has requested this, I haven't found a similar issue, but I might be wrong

Obsidian released it's new "Live preview" editor and after a lot of us requested it, the Obsidian team has been awesome by  allowing Vim to work in the new live editor. 

However my configs from this plugin are not working there. I use the bare essentials, here is my `.obsidian.vimrc` file:

```
" SY / mapping Control + C to work as regular copy to clipboard
unmap <C-c>

" Have j and k navigate visual lines rather than logical ones
nmap j gj
nmap k gk
" I like using H and L for beginning/end of line
nmap H ^
nmap L $
" Quickly remove search highlights
nmap <F9> :nohl

" Yank to system clipboard
set clipboard=unnamed
```

would love to know if it'd be possible for this plugin to work with the new "live preview" editor. Please let me know if there's any way in which I can help, since this would be the only step missing for making things work perfectly with the new editor

Thank you for your great work, huge fun of this plugin!

**Comment by esm7** [comment]
Did you upgrade the plugin to 0.5.0 (released today)?

**Comment by strogiyotec** [comment]
@santiyounger  Same here, upgrading vim plugin solved the issue

**Comment by esm7** [comment]
@santiyounger can you confirm the upgrade to 0.5.0 fixes it for you?

**Comment by linusboyle** [comment]
I have the same issue and upgrading solves the problem

**Comment by esm7** [comment]
Closing; AFAIK the plugin works well for live preview, except the few documented features that don't (and are not part of this issue).
