### ISSUE TITLE
[bug]: Paste using system clipboard

### ISSUE THREAD

**Issue by Jackiexiao** [esm7/obsidian-vimrc-support#7]
while Yank to system clipboard works using, `set clipboard=unnamed`, but paste not

**Comment by esm7** [comment]
You are perfectly right, somehow it didn't cross my mind to also implement the paste side :laughing: :man_facepalming:

**Comment by Jackiexiao** [comment]
could you spend sometime to fix it?

**Comment by esm7** [comment]
Yes, I'll do that once I get to spend some time on the plugin.

**Comment by Jackiexiao** [comment]
thx! when I have time, I will try to learn typescript and write obsidian plugin as well

**Comment by esm7** [comment]
Should be fixed now, please update to the latest version (0.2.1) and let me know if it works as expected.

**Comment by Jackiexiao** [comment]
`Plugin ID mismatch` when I try to update

**Comment by esm7** [comment]
Sorry, fixed now.

**Comment by Jackiexiao** [comment]
solved！thx！
