### ISSUE TITLE
colemak bind not working

### ISSUE THREAD

**Issue by steven130169** [esm7/obsidian-vimrc-support#70]
My keyboard layout is colemak.
This is my vimrc , I want to remap my vimrc.
`
nmap  n j
nmap  e k
`

but it's not working.

https://user-images.githubusercontent.com/27000465/147204394-dda5cb27-d642-4b98-bfd5-4c4d316922e3.mov

**Comment by esm7** [comment]
1. When you map without the vimrc (just type `nmap n j` in Obsidian) does it work?
2. What's your plugin version? If you're using the latest Obsidian you need to update the plugin to 0.5.0.

**Comment by esm7** [comment]
Please check if this happens on 0.5.2, I believe it should work.

**Comment by steven130169** [comment]
Hi @esm7 thanks for your reply. 
But I already have updated to version 0.5.2.
It still doesn't work. 
This's my screen record video.

https://user-images.githubusercontent.com/27000465/147874328-6820f67e-70bb-4d38-879f-8662c55da436.mp4


This is my obsidian-vimrc-support version
<img width="691" alt="CleanShot 2022-01-02 at 19 29 27@2x" src="https://user-images.githubusercontent.com/27000465/147874352-b148cd81-1467-4842-9ab0-efa694c4bd10.png">

This is my obsidian version
<img width="1190" alt="CleanShot 2022-01-02 at 19 30 10@2x" src="https://user-images.githubusercontent.com/27000465/147874368-67587fc7-9061-4d8f-926d-e46384f54a69.png">

This is my OS version
<img width="596" alt="CleanShot 2022-01-02 at 19 30 47@2x" src="https://user-images.githubusercontent.com/27000465/147874384-a326807c-5e0e-4e36-ac83-c3544e7573af.png">

**Comment by esm7** [comment]
When you map without the vimrc (just type `:nmap n j` in Obsidian) does it work?

**Comment by steven130169** [comment]
> When you map without the vimrc (just type `:nmap n j` in Obsidian) does it work?

it's work.

**Comment by esm7** [comment]
Do you mind opening the Obsidian Developer Console (Cmd+Shift+I on Mac I think) and copy/screenshot all the log that you see in the Console tab?

**Comment by steven130169** [comment]
> Do you mind opening the Obsidian Developer Console (Cmd+Shift+I on Mac I think) and copy/screenshot all the log that you see in the Console tab?

<img width="1440" alt="CleanShot 2022-01-02 at 19 42 38@2x" src="https://user-images.githubusercontent.com/27000465/147874665-4b861e2e-9204-48d6-9e7b-dfd6a4be3be2.png">


Wow! I think something wrong.
When I type n in normal mode, the console show me this error.

**Comment by steven130169** [comment]
> Do you mind opening the Obsidian Developer Console (Cmd+Shift+I on Mac I think) and copy/screenshot all the log that you see in the Console tab?

by the way , the Obsidian Developer Console  is command + option + I .

Thanks for your help!

**Comment by esm7** [comment]
That's a good hint. What if you use `noremap` and do `noremap n j` instead of your `nmap`?

**Comment by steven130169** [comment]
> That's a good hint. What if you use `noremap` and do `noremap n j` instead of your `nmap`?

<img width="715" alt="CleanShot 2022-01-02 at 19 50 49@2x" src="https://user-images.githubusercontent.com/27000465/147874837-adb2e600-582a-4c52-96de-008203514779.png">

This vimrc is work. Thank you so much.

**Comment by esm7** [comment]
What seems to happen is that your mappings are recursive (you map `n` to `j`, then `j` to `e`, but `e` is `k`...), so you should be using `noremap`. I suggest you convert all your Vimrc to `noremap`s. Also, the lines in the Vimrc shouldn't start with colons.

**Comment by steven130169** [comment]
> What seems to happen is that your mappings are recursive (you map `n` to `j`, then `j` to `e`, but `e` is `k`...), so you should be using `noremap`. I suggest you convert all your single-letter maps in the Vimrc to `noremap`s. Also, the lines in the Vimrc shouldn't start with colons.

Yes, I already have convert all my maps.
thanks so much.
