### ISSUE TITLE
"nmap j gj" not working for some themes

### ISSUE THREAD

**Issue by kometenstaub** [esm7/obsidian-vimrc-support#72]
First of all, thank you very much for adapting this plugin to cm6! :heart:

I'm not sure if this is the right place, but I noticed something odd.

With themes like [Primary](https://github.com/ceciliamay/obsidianmd-theme-primary) or [Sanctum](https://github.com/jdanielmourao/obsidian-sanctum), if `nmap j gj` is in the vimrc, then I cannot navigate below a heading with `j` or `cursor down` in normal mode. In insert or visual mode it works. (In visual mode, if the mapping `vmap j gj` is active, then it requires `j` two times to go below the heading.)

Instead of going below the line, it goes to the end of it.

![vim-j-headings](https://user-images.githubusercontent.com/83140328/147346866-eebbaec0-69cd-403d-955c-079b3815da2c.gif)

It does work with the base Obsidian theme, so I was wondering if it is up to the theme devs to fix it. [This](https://github.com/jdanielmourao/obsidian-sanctum/blob/7b56154882278d68fa5425ed8597a19c30d6de8f/obsidian.css#L1660) is where the headings css starts for Sanctum, for Primary I cannot link to the line, but you can find it if you search for `Headings`.

I tried a few things with Primary's headings css, but I couldn't get it to work.

Note that it doesn't affect upward motions (`k`).

**Comment by kometenstaub** [comment]
It happens in both `Source` and `Live preview` mode.

**Comment by kometenstaub** [comment]
If click after the heading (so after any text or whitespace), I can go below. If I click on the last character, then I cannot move below it.

**Comment by jdanielmourao** [comment]
Author of Sanctum here! If it happens with Primary and Sanctum, and not many others, it might be interfering with `.cm-s-obsidian .HyperMD-header-1`, etc, which both themes use as part of the heading styling. It's necessary because of things like latex in headings, which can only be targeted with that, afaik.

**Comment by kometenstaub** [comment]
It seems to be impacted by the font size.
When I change the font size to a higher variable (e.g. `--font-scale-4`), then it stops working.

```css
.markdown-preview-view h2,
.HyperMD-header-2,
.cm-header-2 {
    font-size: var(--font-scale-3);
}
```
```css
--font-scale-3: 1.48rem;
--font-scale-4: 1.774rem;
```

**Comment by kometenstaub** [comment]
For others seeing this issue, it isn't a bug with the vimrc plugin, the same can be achieved by remapping manually. I'm leaving this open because this issue will most likely be seen by people who use this plugin.

**Comment by esm7** [comment]
I think it had gotten worse with Obsidian 0.13.27.
It's indeed a bug in Obsidian itself and not this plugin, and I'm actually not sure it was reported to the Obsidian developers properly.

**Comment by kometenstaub** [comment]
It is tracked here https://forum.obsidian.md/t/bug-vim-mode-gj-movement-command-break-with-live-preview-bullets-and-transclusion/31417/

Now also the normal h1 headings are affected, which wasn't the case before. Before it only affected other themes that set the size too high.
