### ISSUE TITLE
Maps to comma don't work

### ISSUE THREAD

**Issue by aith** [esm7/obsidian-vimrc-support#73]
Hey,

It's some time since I've used Obsidian, and I appreciate the work you've put into this plugin since then! However, I have a bug where mappings to comma don't work, such as
``map , o``
or
``noremap , i``
Is this easily fixed?

**Comment by aith** [comment]
Same with these:
``nmap k <C-d>
nmap . <C-u>
``
In the inspector Console tab, there are no error messages. When using the commands manually, they work. Is it possible that these mappings are being overwritten by a later mapping?

**Comment by esm7** [comment]
This is hopefully fixed in 0.5.2 which I just released, can you upgrade and verify?

**Comment by aith** [comment]
Hey esm7, I updated to 0.5.2 and sadly none of the issues have been resolved

**Comment by esm7** [comment]
This is strange, all of these mappings work for me.
1. Could it be that the plugin doesn't work for you at all? Do you have other mappings in your Vimrc that do work?
2. Are you using the Obsidian legacy editor or the new one?
3. Can you screenshot your plugin configuration page or attach the settings json file?
4. Which version of Obsidian?
5. Although you already noted you see no errors in the console tab, can you screenshot or copy it so I can see the other (non-error logs?

**Comment by aith** [comment]
1) I have a large number of mappings in my vimrc and most do work!
2) I tried both legacy and non-legacy and I still run into the issue on both.
3) Here's the config file under ~/obsidian/.obsidian/config:
```
{"pluginEnabledStatus":{"file-explorer":true,"global-search":true,"switcher":true,"graph":true,"backlink":true,"command-palette":true,"markdown-importer":true,"word-count":true,"open-with-default-app":true,"file-recovery":true},"promptDelete":false,"enabledPlugins":["obsidian-vimrc-support"],"vimMode":true,"hotkeys":{"editor:toggle-fold":[{"modifiers":["Mod"],"key":"T"}],"editor:insert-link":[{"modifiers":["Mod"],"key":"Y"}],"command-palette:open":[{"modifiers":["Mod"],"key":"'"}]},"theme":"moonstone"}
```
4) I'm using version 0.13.19 (the latest one)
5) It's empty, but here's what it looks like after trying the keys I tried to map to.
![console](https://user-images.githubusercontent.com/62635784/150603031-fb83dbeb-c7ce-4fb1-ad48-698846ce2523.png)

**Comment by aith** [comment]
Also, here's my ~/obsidian/.obsidian.vimrc:
```
nmap , o
nmap a j
nmap e k
nmap i h
nmap o l
nmap j ;
nmap r i
nmap l e
nmap L E
nmap H B
nmap h b
nmap n a
nmap N A
nmap t w
nmap T W
nmap w ^
nmap ; $
nmap b t
nmap R I
nmap B T
nmap j n
nmap < O
nmap <C-,> <
nmap <C-.> >
nmap Y y$n
nmap D d$
nmap C c$
nmap Q @
nmap = .
nmap <C-j> J
nmap J N
nmap P ^
nmap <BS> x
nmap m ge
nmap M gE
nmap + .
nmap = %
nmap _ > 
nmap - <
nmap <C--> <C-x>
nmap <C-=> <C-a>
nmap <M-,> <C-o>
nmap <C-M-,> <C-i>
nmap <C-;> A 
nmap k <C-d>
nmap . <C-u>
```

**Comment by aith** [comment]
Reset my vault and found it worked- my vimrc was likely placed in the wrong location!
