### ISSUE TITLE
imap df <Esc> not working

### ISSUE THREAD

**Issue by olof-ynwa** [esm7/obsidian-vimrc-support#74]
I'm using a simple .vimrc file with the following two lines.
`imap df <Esc>`
`imap fd <Esc>`

When vim mode display is enabled, vim breaks, I cannot enter insert mode, I can only write a bunch of i's or a's, After writing an i or a it seems as if Obsidian vim enter normal mode automatically.
When vim mode display isn't enabled, nothing happens, it's as if the commands haven't been executed.

The two lines work when they're executed manually in Obsidian vim normal mode.

**Comment by esm7** [comment]
I believe this is fixed in 0.5.2 which I just released, can you upgrade and verify?

**Comment by olof-ynwa** [comment]
Yes, it works now  :-).
