### ISSUE TITLE
command showing in header

### ISSUE THREAD

**Issue by dolphinpoint** [esm7/obsidian-vimrc-support#77]
Uou are probably already aware of this, but obcommand's are visible in the live preview note header despite chord display being disabled. 

https://user-images.githubusercontent.com/45613877/147843396-a493df58-aa2c-4bc5-a6b8-de7ef4f0f80b.mp4

**Comment by esm7** [comment]
I was not aware and it looks terribly annoying, thank you!

**Comment by esm7** [comment]
I was unable to recreate this, however it might be related to some other fixes that I did as part of version 0.5.2.
Do you mind checking if this still happens on 0.5.2, and if so, help me out with more details on how you get to this issue?
- What editor are you using (legacy or new)?
- What theme is it?
- How does your Vimrc look like?
- How does the plugin configuration look like?

**Comment by dolphinpoint** [comment]
Sorry for the late reply. The problem fixed with your most recent update. Thanks!
