### ISSUE TITLE
The plugin doens't seem to work when LivePreview is enabled

### ISSUE THREAD

**Issue by nonsleepr** [esm7/obsidian-vimrc-support#79]
New [LivePreview](https://help.obsidian.md/Live+preview+update) feature introduced in Obsidian 0.13 prevents the plugin from working.

**Comment by esm7** [comment]
Please upgrade to the latest version of the plugin.

**Comment by nonsleepr** [comment]
Oh, I'm sorry I forgot to try that. It works indeed.
