### ISSUE TITLE
noremaps of 'o' do not work

### ISSUE THREAD

**Issue by aith** [esm7/obsidian-vimrc-support#85]
Hi! I appreciate the work you've done with this plugin. I only have one issue left with my key mappings, and it's that any noremaps of 'o' won't work. For example, none of the following commands apply the change:

```
noremap x o
noremap , o
noremap - o
```
Any thoughts?

**Comment by esm7** [comment]
I'm not sure why, but this works only with regular `nmap`.
Note this is a CodeMirror issue and not the plugin's. The CodeMirror Vim support often requires lots of trial and error to get to something that works :-/
