### ISSUE TITLE
:obcommand does not work when .obsidian.vimrc is not present in $VAULT_ROOT

### ISSUE THREAD

**Issue by webdog** [esm7/obsidian-vimrc-support#89]
👋 

Thank you for this plugin!

I noticed that when enabling the plugin, but not creating a vimrc file after installation, `:obcommand` does not work. An error is returned in the gutter: ":obcommand is not an editor command`

By creating an empty .obsidian.vimrc file, `obcommand` is expected.

In the [Usage](https://github.com/esm7/obsidian-vimrc-support#usage) section, it's mentioned to create the vimrc to persist mappings, but I didn't understand this as the plugin-specific command wouldn't work unless the rc file was loaded.

From having other obsidian plugins installed, I wasn't expecting to need to create an rc file right away to have functionality. Other plugins seem to work without specifying a config file, in previous experiences.

Again thank you for this plugin, it's very useful 😸

**Comment by esm7** [comment]
Well, this came as a surprise: the plugin was originally meant to simply persist settings that you could apply either way, but it now contains some more stuff that could be useful either way...
So I untied the registration of the other ex commands from loading the Vimrc file, and as of 0.6.0 the file doesn't need to exist for the other functionality to work.
