### ISSUE TITLE
"Plugin ID mismatch" when trying to install Version 0.2.1

### ISSUE THREAD

**Issue by mtran45** [esm7/obsidian-vimrc-support#9]
I currently have 0.2.0 of this plugin installed, and when I try to update to 0.2.1, it throws a "Plugin ID mismatch" error.

I've tried to uninstall 0.2.0 and install 0.2.1 and it still throws the same error.

I'm using Obsidian v0.9.22 on Windows.

**Comment by esm7** [comment]
So sorry about that :( Fixed it now.

**Comment by mtran45** [comment]
No worries! Thanks for the speedy response
