### ISSUE TITLE
[Feat] ability to take mdHelpers.js file to a folder other than the root node

### ISSUE THREAD

**Issue by 23727** [esm7/obsidian-vimrc-support#93]
Thank you for the js support. I was wondering if we can have the option to change the js file location like we have for the vimrc file?

I tried moving the js helper from the root of the vault but the plug-in could not find it

**Comment by esm7** [comment]
If you specify a path within the vault it should work, e.g. `jsfile code/mdHelpers.js`

**Comment by 23727** [comment]
Thanks for helping. 

Can you guide me to where I can specify the path? 

I didn't see a place to do it in the Vimrc Settings page. Am I able to do it through one of the Vimrc code files specifically?

**Comment by 23727** [comment]
My mistake, I saw that it is in the actual vimrc file that gives the js file command. Thank you!
